# docker build -t clion-vnc:0.1 ./
# put jetbrains_jdk(fix https://blog.csdn.net/Startapi/article/details/108851425) to /workspace
# docker run -d -p 5901:5901 -p 6901:6901 --user $(id -u):$(id -g) -e VNC_RESOLUTION=1920x1080 -v /workspace:/workspace clion-vnc:0.1
# docker run -it --rm -p 5901:5901 -p 6901:6901 --user 0 -e VNC_RESOLUTION=1920x1080 -v /workspace:/workspace clion-vnc:0.2 bash
# more document: https://github.com/ConSol/docker-headless-vnc-container
FROM consol/ubuntu-xfce-vnc:1.4.0

# Switch to root user to install additional software
USER 0

ENV CLION_VERSION=2020.3

# clion
RUN cd /tmp \
    && wget https://download-cf.jetbrains.com/cpp/CLion-${CLION_VERSION}.tar.gz \
    && tar xvzf CLion-*.tar.gz -C /opt/ \
    && rm ./*.tar.gz \
    && mkdir -p ~/Desktop \
    && cd ~/Desktop \
    && sed -i '2i\export CLION_JDK="/workspace/jetbrains_jdk"' /opt/clion-${CLION_VERSION}/bin/clion.sh \
    && ln -s /opt/clion-${CLION_VERSION}/bin/clion.sh clion.sh

ENV SOGOU_PY_VERSION=2.4.0.2732_amd64

RUN cd /tmp \
    # install other lib
    && apt-get update -yqq \
    && apt-get install -yqq gcc-4.9 g++-4.9 git gedit silversearcher-ag fcitx \
    && ln -s /usr/bin/g++-4.9 /usr/bin/g++ \
    && ln -s /usr/bin/gcc-4.9 /usr/bin/gcc \
    && wget https://ime.sogoucdn.com/dl/index/1605612770/sogoupinyin_${SOGOU_PY_VERSION}.deb \
    && apt-get install -yqq ./sogoupinyin_${SOGOU_PY_VERSION}.deb \
    && apt-get clean \
    && rm -rf \
    /var/lib/apt/lists/* \
    /tmp/* \
    /var/tmp/* \
    /usr/share/man \
    /usr/share/doc \
    /usr/share/doc-base

ENV GTK_IM_MODULE="fcitx"
ENV QT_IM_MODULE="fcitx"
ENV XMODIFIERS="@im=fcitx"

## switch back to default user
USER 1000
